const express = require("express");
const app = express();
const axios = require("axios");
app.use(express.json());
const port = 3005;

process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

app.use((req, res, next) => {
  res.header("Access-Control-Allow-Origin", "*");
  res.header(
    "Access-Control-Allow-Headers",
    "Origin, X-Requested-With, Content-Type, Accept"
  );
  next();
});

const sessionObj = {
  sessionId: null,
  sessionTime: null,
};

const loginToSAPSession = async () => {
  try {
    const response = await axios.post(
      "https://192.168.0.44:50000/b1s/v1/Login",
      {
        CompanyDB: "Homart_TEST8",
        UserName: "SAPCreatio",
        Password: "Bold#By68",
      }
    );
    console.log(
      "response.headers['set-cookie']:",
      response.headers["set-cookie"]
    );
    console.log("response.data:" + response.data);

    const cookies = response.headers["set-cookie"];
    const b1SessionCookie = cookies
      .find((cookie) => cookie.startsWith("B1SESSION="))
      .split(";")[0];
    const routeIdCookie = cookies
      .find((cookie) => cookie.startsWith("ROUTEID="))
      .split(";")[0];
    const cookie = [b1SessionCookie, routeIdCookie].join("; ");

    sessionObj.sessionId = cookie;
  } catch (error) {
    console.log("error.message:" + error.message);
  }
};

app.post("/api/login", async (req, res) => {
  await loginToSAPSession();
  res.send({ message: "Logged in to SAP session" });
});

// User SAP account verify
app.post("/api/userAccount", async (req, res) => {
  console.log("req.body:", req.body);
  const checkAccountBaseURL = `https://192.168.0.44:50000/b1s/v1/view.svc/Homart_CheckUserAccount_B1SLQuery()?$filter=U_UserCode eq '${req.body.sapusername}' and U_UserPW eq '${req.body.sappassword}'`;
  console.log(checkAccountBaseURL);
  console.log("sessionObj.sessionId: " + sessionObj.sessionId);
  try {
    const response = await axios.get(checkAccountBaseURL, {
      withCredentials: true,
      headers: {
        Cookie: sessionObj.sessionId,
      },
    });
    const count = response.data.value.length;
    res.send({ count });
  } catch (error) {
    console.log("error.message:", error.message);
    res.status(500).send(error.message);
  }

  //   Sample Response if username and password matched, if not matched, count = 0
  //   {
  //     "count": 1
  // }
});

// Batch number details
app.post("/api/batchnumberdetail", async (req, res) => {
  console.log("req.body:", req.body);
  const getItemByBatchBaseURL = `https://192.168.0.44:50000/b1s/v1/BatchNumberDetails?$filter=Batch eq '${req.body.BatchNumber}'`;
  console.log(getItemByBatchBaseURL);
  console.log("sessionObj.sessionId: " + sessionObj.sessionId);
  try {
    const response = await axios.get(getItemByBatchBaseURL, {
      withCredentials: true,
      headers: {
        Cookie: sessionObj.sessionId,
        Prefer: "odata.maxpagesize=9999999999",
      },
    });
    res.send(response.data);
  } catch (error) {
    console.log("error.message:", error.message);
    res.status(500).send(error.message);
  }

  //   Sample Response
  // {
  //     "odata.metadata": "https://192.168.0.44:50000/b1s/v1/$metadata#BatchNumberDetails",
  //     "value": [
  //         {
  //             "DocEntry": 19425,
  //             "ItemCode": "PB300-0010",
  //             "ItemDescription": "Bottle 1HOM RA300ml Amber PET Bottle - JX",
  //             "Status": "bdsStatus_Released",
  //             "Batch": "H36592",
  //             "BatchAttribute1": "S00403-Homart OEM",
  //             "BatchAttribute2": null,
  //             "AdmissionDate": "2023-03-08",
  //             "ManufacturingDate": null,
  //             "ExpirationDate": null,
  //             "Details": null,
  //             "SystemNumber": 89,
  //             "U_DateReleased": "2023-03-31",
  //             "U_DateProcessed": null,
  //             "U_PestReason": null,
  //             "U_PackingSign": null,
  //             "U_LabelSample": null,
  //             "U_MilkSign": null,
  //             "U_Origin": null,
  //             "U_AQISNo": null,
  //             "U_F03H": null,
  //             "U_TransDelReced": null,
  //             "U_TransDelAccept": null,
  //             "U_ClaimedQty": 19040,
  //             "U_ShipperDamaged": "P",
  //             "U_DamagedReason": null,
  //             "U_ShipperLabel": "P",
  //             "U_LabelReason": null,
  //             "U_PestCheck": "P",
  //             "U_COAWeight": null,
  //             "U_WarehouseComment": "(2P*16C+12C+8C)*272+(28C+8C)*136=19040",
  //             "U_SuppCatNum": null,
  //             "U_SupplierCode": "S00014-浙江上虞市佳星塑料製品有限公司 RMB/JX",
  //             "U_GRPO": "GRPO",
  //             "U_InventoryUoM": "each",
  //             "U_AllowBatchDup": "N",
  //             "U_Manufacturer": null,
  //             "U_DeliveryNo": null,
  //             "U_InventoryNotes": null,
  //             "U_TestBeforeUse": "N"
  //         }
  //     ]
  // }
});

// Items
app.post("/api/items", async (req, res) => {
  console.log("req.body:", req.body);
  const getItemDetailByItemNumberBaseURL = `https://192.168.0.44:50000/b1s/v1/Items('${req.body.ItemNumber}')`;
  console.log(getItemDetailByItemNumberBaseURL);
  console.log("sessionObj.sessionId: " + sessionObj.sessionId);
  try {
    const response = await axios.get(getItemDetailByItemNumberBaseURL, {
      withCredentials: true,
      headers: {
        Cookie: sessionObj.sessionId,
        Prefer: "odata.maxpagesize=9999999999",
      },
    });
    res.send(response.data);
  } catch (error) {
    console.log("error.message:", error.message);
    res.status(500).send(error.message);
  }
  //   Sample Response
//   {
//     "odata.metadata": "https://192.168.0.44:50000/b1s/v1/$metadata#Items/@Element",
//     "odata.etag": "W/\"DA4B9237BACCCDF19C0760CAB7AEC4A8359010B0\"",
//     "ItemCode": "PLPID-0006",
//     "ItemName": "Label 1BSP Performance Inspired Turmeric Curcumin 120s",
//     "ForeignName": "Label Performance Inspired Turmeric Curcumin 120s",
//     "ItemsGroupCode": 113,
//     "CustomsGroupCode": -1,
//     "SalesVATGroup": "S1",
//     "BarCode": null,
//     "VatLiable": "tYES",
//     "PurchaseItem": "tYES",
//     "SalesItem": "tYES",
//     "InventoryItem": "tYES",
//     "IncomeAccount": null,
//     "ExemptIncomeAccount": null,
//     "ExpanseAccount": null,
//     "Mainsupplier": null,
//     "SupplierCatalogNo": null,
//     "DesiredInventory": 0,
//     "MinInventory": 0,
//     "Picture": null,
//     "User_Text": null,
//     "SerialNum": null,
//     "CommissionPercent": 0,
//     "CommissionSum": 0,
//     "CommissionGroup": 0,
//     "TreeType": "iNotATree",
//     "AssetItem": "tNO",
//     "DataExportCode": null,
//     "Manufacturer": -1,
//     "QuantityOnStock": 227,
//     "QuantityOrderedFromVendors": 0,
//     "QuantityOrderedByCustomers": 0,
//     "ManageSerialNumbers": "tNO",
//     "ManageBatchNumbers": "tYES",
//     "Valid": "tYES",
//     "ValidFrom": null,
//     "ValidTo": null,
//     "ValidRemarks": null,
//     "Frozen": "tNO",
//     "FrozenFrom": null,
//     "FrozenTo": null,
//     "FrozenRemarks": null,
//     "SalesUnit": "1000",
//     "SalesItemsPerUnit": 1000,
//     "SalesPackagingUnit": null,
//     "SalesQtyPerPackUnit": 1,
//     "SalesUnitLength": null,
//     "SalesLengthUnit": null,
//     "SalesUnitWidth": null,
//     "SalesWidthUnit": null,
//     "SalesUnitHeight": null,
//     "SalesHeightUnit": null,
//     "SalesUnitVolume": 0,
//     "SalesVolumeUnit": 4,
//     "SalesUnitWeight": null,
//     "SalesWeightUnit": null,
//     "PurchaseUnit": "1000",
//     "PurchaseItemsPerUnit": 1000,
//     "PurchasePackagingUnit": null,
//     "PurchaseQtyPerPackUnit": 1,
//     "PurchaseUnitLength": null,
//     "PurchaseLengthUnit": null,
//     "PurchaseUnitWidth": null,
//     "PurchaseWidthUnit": null,
//     "PurchaseUnitHeight": null,
//     "PurchaseHeightUnit": null,
//     "PurchaseUnitVolume": 0,
//     "PurchaseVolumeUnit": 4,
//     "PurchaseUnitWeight": null,
//     "PurchaseWeightUnit": null,
//     "PurchaseVATGroup": "P1",
//     "SalesFactor1": 1,
//     "SalesFactor2": 1,
//     "SalesFactor3": 1,
//     "SalesFactor4": 1,
//     "PurchaseFactor1": 1,
//     "PurchaseFactor2": 1,
//     "PurchaseFactor3": 1,
//     "PurchaseFactor4": 1,
//     "MovingAveragePrice": 0.102,
//     "ForeignRevenuesAccount": null,
//     "ECRevenuesAccount": null,
//     "ForeignExpensesAccount": null,
//     "ECExpensesAccount": null,
//     "AvgStdPrice": 0.102,
//     "DefaultWarehouse": "WCP",
//     "ShipType": 19,
//     "GLMethod": "glm_ItemClass",
//     "TaxType": "tt_Yes",
//     "MaxInventory": 0,
//     "ManageStockByWarehouse": "tNO",
//     "PurchaseHeightUnit1": null,
//     "PurchaseUnitHeight1": null,
//     "PurchaseLengthUnit1": null,
//     "PurchaseUnitLength1": null,
//     "PurchaseWeightUnit1": null,
//     "PurchaseUnitWeight1": null,
//     "PurchaseWidthUnit1": null,
//     "PurchaseUnitWidth1": null,
//     "SalesHeightUnit1": null,
//     "SalesUnitHeight1": null,
//     "SalesLengthUnit1": null,
//     "SalesUnitLength1": null,
//     "SalesWeightUnit1": null,
//     "SalesUnitWeight1": null,
//     "SalesWidthUnit1": null,
//     "SalesUnitWidth1": null,
//     "ForceSelectionOfSerialNumber": "tYES",
//     "ManageSerialNumbersOnReleaseOnly": "tNO",
//     "WTLiable": "tNO",
//     "CostAccountingMethod": "bis_MovingAverage",
//     "SWW": null,
//     "WarrantyTemplate": "",
//     "IndirectTax": "tNO",
//     "ArTaxCode": null,
//     "ApTaxCode": null,
//     "BaseUnitName": null,
//     "ItemCountryOrg": null,
//     "IssueMethod": "im_Manual",
//     "SRIAndBatchManageMethod": "bomm_OnEveryTransaction",
//     "IsPhantom": "tNO",
//     "InventoryUOM": "each",
//     "PlanningSystem": "bop_MRP",
//     "ProcurementMethod": "bom_Buy",
//     "ComponentWarehouse": "bomcw_BOM",
//     "OrderIntervals": null,
//     "OrderMultiple": 0,
//     "LeadTime": null,
//     "MinOrderQuantity": 0,
//     "ItemType": "itItems",
//     "ItemClass": "itcMaterial",
//     "OutgoingServiceCode": -1,
//     "IncomingServiceCode": -1,
//     "ServiceGroup": -1,
//     "NCMCode": -1,
//     "MaterialType": "mt_FinishedGoods",
//     "MaterialGroup": -1,
//     "ProductSource": "",
//     "Properties1": "tNO",
//     "Properties2": "tNO",
//     "Properties3": "tNO",
//     "Properties4": "tNO",
//     "Properties5": "tNO",
//     "Properties6": "tNO",
//     "Properties7": "tNO",
//     "Properties8": "tNO",
//     "Properties9": "tNO",
//     "Properties10": "tNO",
//     "Properties11": "tNO",
//     "Properties12": "tNO",
//     "Properties13": "tNO",
//     "Properties14": "tYES",
//     "Properties15": "tNO",
//     "Properties16": "tNO",
//     "Properties17": "tNO",
//     "Properties18": "tNO",
//     "Properties19": "tNO",
//     "Properties20": "tNO",
//     "Properties21": "tNO",
//     "Properties22": "tNO",
//     "Properties23": "tNO",
//     "Properties24": "tNO",
//     "Properties25": "tNO",
//     "Properties26": "tNO",
//     "Properties27": "tNO",
//     "Properties28": "tNO",
//     "Properties29": "tNO",
//     "Properties30": "tNO",
//     "Properties31": "tNO",
//     "Properties32": "tNO",
//     "Properties33": "tNO",
//     "Properties34": "tNO",
//     "Properties35": "tNO",
//     "Properties36": "tNO",
//     "Properties37": "tNO",
//     "Properties38": "tNO",
//     "Properties39": "tNO",
//     "Properties40": "tNO",
//     "Properties41": "tNO",
//     "Properties42": "tNO",
//     "Properties43": "tNO",
//     "Properties44": "tNO",
//     "Properties45": "tNO",
//     "Properties46": "tNO",
//     "Properties47": "tNO",
//     "Properties48": "tNO",
//     "Properties49": "tNO",
//     "Properties50": "tNO",
//     "Properties51": "tNO",
//     "Properties52": "tNO",
//     "Properties53": "tNO",
//     "Properties54": "tNO",
//     "Properties55": "tNO",
//     "Properties56": "tNO",
//     "Properties57": "tNO",
//     "Properties58": "tNO",
//     "Properties59": "tNO",
//     "Properties60": "tNO",
//     "Properties61": "tNO",
//     "Properties62": "tNO",
//     "Properties63": "tNO",
//     "Properties64": "tNO",
//     "AutoCreateSerialNumbersOnRelease": "tNO",
//     "DNFEntry": -1,
//     "GTSItemSpec": null,
//     "GTSItemTaxCategory": null,
//     "FuelID": null,
//     "BeverageTableCode": "",
//     "BeverageGroupCode": "",
//     "BeverageCommercialBrandCode": null,
//     "Series": 3,
//     "ToleranceDays": null,
//     "TypeOfAdvancedRules": "toarGeneral",
//     "IssuePrimarilyBy": "ipbSerialAndBatchNumbers",
//     "NoDiscounts": "tNO",
//     "AssetClass": "",
//     "AssetGroup": "",
//     "InventoryNumber": "",
//     "Technician": null,
//     "Employee": null,
//     "Location": null,
//     "AssetStatus": "New",
//     "CapitalizationDate": null,
//     "StatisticalAsset": "tNO",
//     "Cession": "tNO",
//     "DeactivateAfterUsefulLife": "tNO",
//     "ManageByQuantity": "tNO",
//     "UoMGroupEntry": -1,
//     "InventoryUoMEntry": -1,
//     "DefaultSalesUoMEntry": null,
//     "DefaultPurchasingUoMEntry": null,
//     "DepreciationGroup": null,
//     "AssetSerialNumber": "",
//     "InventoryWeight": null,
//     "InventoryWeightUnit": null,
//     "InventoryWeight1": null,
//     "InventoryWeightUnit1": null,
//     "DefaultCountingUnit": null,
//     "CountingItemsPerUnit": 1,
//     "DefaultCountingUoMEntry": null,
//     "Excisable": "tNO",
//     "ChapterID": -1,
//     "ScsCode": null,
//     "SpProdType": null,
//     "ProdStdCost": 0,
//     "InCostRollup": "tYES",
//     "VirtualAssetItem": "tNO",
//     "EnforceAssetSerialNumbers": "tNO",
//     "AttachmentEntry": null,
//     "LinkedResource": null,
//     "UpdateDate": "2022-05-13",
//     "UpdateTime": "11:41:26",
//     "GSTRelevnt": "tNO",
//     "SACEntry": -1,
//     "GSTTaxCategory": "gtc_Regular",
//     "ServiceCategoryEntry": -1,
//     "CapitalGoodsOnHoldPercent": null,
//     "CapitalGoodsOnHoldLimit": null,
//     "AssessableValue": 0,
//     "AssVal4WTR": 0,
//     "SOIExcisable": "se_NotExcisable",
//     "TNVED": null,
//     "ImportedItem": "tNO",
//     "PricingUnit": -1,
//     "CreateDate": "2022-05-13",
//     "CreateTime": "11:41:26",
//     "NVECode": null,
//     "CtrSealQty": null,
//     "CESTCode": -1,
//     "LegalText": null,
//     "DataVersion": 2,
//     "CreateQRCodeFrom": null,
//     "TraceableItem": "tNO",
//     "U_MYOBItemCode": null,
//     "U_WFPLocation": null,
//     "U_Compatiable": "0",
//     "U_QAVersion": null,
//     "U_Manufacturers": null,
//     "ItemPrices": [
//         {
//             "PriceList": 1,
//             "Price": 0,
//             "Currency": "",
//             "AdditionalPrice1": 0,
//             "AdditionalCurrency1": "",
//             "AdditionalPrice2": 0,
//             "AdditionalCurrency2": "",
//             "BasePriceList": 1,
//             "Factor": 1,
//             "UoMPrices": []
//         },
//         {
//             "PriceList": 2,
//             "Price": 0,
//             "Currency": "",
//             "AdditionalPrice1": 0,
//             "AdditionalCurrency1": "",
//             "AdditionalPrice2": 0,
//             "AdditionalCurrency2": "",
//             "BasePriceList": 2,
//             "Factor": 1,
//             "UoMPrices": []
//         },
//         {
//             "PriceList": 3,
//             "Price": 0,
//             "Currency": "",
//             "AdditionalPrice1": 0,
//             "AdditionalCurrency1": "",
//             "AdditionalPrice2": 0,
//             "AdditionalCurrency2": "",
//             "BasePriceList": 3,
//             "Factor": 1,
//             "UoMPrices": []
//         },
//         {
//             "PriceList": 4,
//             "Price": 0,
//             "Currency": "",
//             "AdditionalPrice1": 0,
//             "AdditionalCurrency1": "",
//             "AdditionalPrice2": 0,
//             "AdditionalCurrency2": "",
//             "BasePriceList": 4,
//             "Factor": 1,
//             "UoMPrices": []
//         },
//         {
//             "PriceList": 5,
//             "Price": 0,
//             "Currency": "",
//             "AdditionalPrice1": 0,
//             "AdditionalCurrency1": "",
//             "AdditionalPrice2": 0,
//             "AdditionalCurrency2": "",
//             "BasePriceList": 5,
//             "Factor": 1,
//             "UoMPrices": []
//         },
//         {
//             "PriceList": 6,
//             "Price": 0,
//             "Currency": "",
//             "AdditionalPrice1": 0,
//             "AdditionalCurrency1": "",
//             "AdditionalPrice2": 0,
//             "AdditionalCurrency2": "",
//             "BasePriceList": 6,
//             "Factor": 1,
//             "UoMPrices": []
//         }
//     ],
//     "ItemWarehouseInfoCollection": [
//         {
//             "MinimalStock": 0,
//             "MaximalStock": 0,
//             "MinimalOrder": 0,
//             "StandardAveragePrice": 0,
//             "Locked": "tNO",
//             "InventoryAccount": null,
//             "CostAccount": null,
//             "TransferAccount": null,
//             "RevenuesAccount": null,
//             "VarienceAccount": null,
//             "DecreasingAccount": null,
//             "IncreasingAccount": null,
//             "ReturningAccount": null,
//             "ExpensesAccount": null,
//             "EURevenuesAccount": null,
//             "EUExpensesAccount": null,
//             "ForeignRevenueAcc": null,
//             "ForeignExpensAcc": null,
//             "ExemptIncomeAcc": null,
//             "PriceDifferenceAcc": null,
//             "WarehouseCode": "W3P",
//             "InStock": 0,
//             "Committed": 0,
//             "Ordered": 0,
//             "CountedQuantity": 0,
//             "WasCounted": "tNO",
//             "UserSignature": 20,
//             "Counted": 0,
//             "ExpenseClearingAct": null,
//             "PurchaseCreditAcc": null,
//             "EUPurchaseCreditAcc": null,
//             "ForeignPurchaseCreditAcc": null,
//             "SalesCreditAcc": null,
//             "SalesCreditEUAcc": null,
//             "ExemptedCredits": null,
//             "SalesCreditForeignAcc": null,
//             "ExpenseOffsettingAccount": null,
//             "WipAccount": null,
//             "ExchangeRateDifferencesAcct": null,
//             "GoodsClearingAcct": null,
//             "NegativeInventoryAdjustmentAccount": null,
//             "CostInflationOffsetAccount": null,
//             "GLDecreaseAcct": null,
//             "GLIncreaseAcct": null,
//             "PAReturnAcct": null,
//             "PurchaseAcct": null,
//             "PurchaseOffsetAcct": null,
//             "ShippedGoodsAccount": null,
//             "StockInflationOffsetAccount": null,
//             "StockInflationAdjustAccount": null,
//             "VATInRevenueAccount": null,
//             "WipVarianceAccount": null,
//             "CostInflationAccount": null,
//             "WHIncomingCenvatAccount": null,
//             "WHOutgoingCenvatAccount": null,
//             "StockInTransitAccount": null,
//             "WipOffsetProfitAndLossAccount": null,
//             "InventoryOffsetProfitAndLossAccount": null,
//             "DefaultBin": null,
//             "DefaultBinEnforced": "tNO",
//             "PurchaseBalanceAccount": null,
//             "ItemCode": "PLPID-0006",
//             "IndEscala": "tYES",
//             "CNJPMan": null,
//             "ItemCycleCounts": []
//         },
//         {
//             "MinimalStock": 0,
//             "MaximalStock": 0,
//             "MinimalOrder": 0,
//             "StandardAveragePrice": 0,
//             "Locked": "tNO",
//             "InventoryAccount": null,
//             "CostAccount": null,
//             "TransferAccount": null,
//             "RevenuesAccount": null,
//             "VarienceAccount": null,
//             "DecreasingAccount": null,
//             "IncreasingAccount": null,
//             "ReturningAccount": null,
//             "ExpensesAccount": null,
//             "EURevenuesAccount": null,
//             "EUExpensesAccount": null,
//             "ForeignRevenueAcc": null,
//             "ForeignExpensAcc": null,
//             "ExemptIncomeAcc": null,
//             "PriceDifferenceAcc": null,
//             "WarehouseCode": "W3Q",
//             "InStock": 0,
//             "Committed": 0,
//             "Ordered": 0,
//             "CountedQuantity": 0,
//             "WasCounted": "tNO",
//             "UserSignature": 1,
//             "Counted": 0,
//             "ExpenseClearingAct": null,
//             "PurchaseCreditAcc": null,
//             "EUPurchaseCreditAcc": null,
//             "ForeignPurchaseCreditAcc": null,
//             "SalesCreditAcc": null,
//             "SalesCreditEUAcc": null,
//             "ExemptedCredits": null,
//             "SalesCreditForeignAcc": null,
//             "ExpenseOffsettingAccount": null,
//             "WipAccount": null,
//             "ExchangeRateDifferencesAcct": null,
//             "GoodsClearingAcct": null,
//             "NegativeInventoryAdjustmentAccount": null,
//             "CostInflationOffsetAccount": null,
//             "GLDecreaseAcct": null,
//             "GLIncreaseAcct": null,
//             "PAReturnAcct": null,
//             "PurchaseAcct": null,
//             "PurchaseOffsetAcct": null,
//             "ShippedGoodsAccount": null,
//             "StockInflationOffsetAccount": null,
//             "StockInflationAdjustAccount": null,
//             "VATInRevenueAccount": null,
//             "WipVarianceAccount": null,
//             "CostInflationAccount": null,
//             "WHIncomingCenvatAccount": null,
//             "WHOutgoingCenvatAccount": null,
//             "StockInTransitAccount": null,
//             "WipOffsetProfitAndLossAccount": null,
//             "InventoryOffsetProfitAndLossAccount": null,
//             "DefaultBin": null,
//             "DefaultBinEnforced": "tNO",
//             "PurchaseBalanceAccount": null,
//             "ItemCode": "PLPID-0006",
//             "IndEscala": "tYES",
//             "CNJPMan": null,
//             "ItemCycleCounts": []
//         },
//         {
//             "MinimalStock": 0,
//             "MaximalStock": 0,
//             "MinimalOrder": 0,
//             "StandardAveragePrice": 0,
//             "Locked": "tNO",
//             "InventoryAccount": null,
//             "CostAccount": null,
//             "TransferAccount": null,
//             "RevenuesAccount": null,
//             "VarienceAccount": null,
//             "DecreasingAccount": null,
//             "IncreasingAccount": null,
//             "ReturningAccount": null,
//             "ExpensesAccount": null,
//             "EURevenuesAccount": null,
//             "EUExpensesAccount": null,
//             "ForeignRevenueAcc": null,
//             "ForeignExpensAcc": null,
//             "ExemptIncomeAcc": null,
//             "PriceDifferenceAcc": null,
//             "WarehouseCode": "WCP",
//             "InStock": 227,
//             "Committed": 0,
//             "Ordered": 0,
//             "CountedQuantity": 0,
//             "WasCounted": "tNO",
//             "UserSignature": 20,
//             "Counted": 0,
//             "ExpenseClearingAct": null,
//             "PurchaseCreditAcc": null,
//             "EUPurchaseCreditAcc": null,
//             "ForeignPurchaseCreditAcc": null,
//             "SalesCreditAcc": null,
//             "SalesCreditEUAcc": null,
//             "ExemptedCredits": null,
//             "SalesCreditForeignAcc": null,
//             "ExpenseOffsettingAccount": null,
//             "WipAccount": null,
//             "ExchangeRateDifferencesAcct": null,
//             "GoodsClearingAcct": null,
//             "NegativeInventoryAdjustmentAccount": null,
//             "CostInflationOffsetAccount": null,
//             "GLDecreaseAcct": null,
//             "GLIncreaseAcct": null,
//             "PAReturnAcct": null,
//             "PurchaseAcct": null,
//             "PurchaseOffsetAcct": null,
//             "ShippedGoodsAccount": null,
//             "StockInflationOffsetAccount": null,
//             "StockInflationAdjustAccount": null,
//             "VATInRevenueAccount": null,
//             "WipVarianceAccount": null,
//             "CostInflationAccount": null,
//             "WHIncomingCenvatAccount": null,
//             "WHOutgoingCenvatAccount": null,
//             "StockInTransitAccount": null,
//             "WipOffsetProfitAndLossAccount": null,
//             "InventoryOffsetProfitAndLossAccount": null,
//             "DefaultBin": null,
//             "DefaultBinEnforced": "tNO",
//             "PurchaseBalanceAccount": null,
//             "ItemCode": "PLPID-0006",
//             "IndEscala": "tYES",
//             "CNJPMan": null,
//             "ItemCycleCounts": []
//         },
//         {
//             "MinimalStock": 0,
//             "MaximalStock": 0,
//             "MinimalOrder": 0,
//             "StandardAveragePrice": 0,
//             "Locked": "tNO",
//             "InventoryAccount": null,
//             "CostAccount": null,
//             "TransferAccount": null,
//             "RevenuesAccount": null,
//             "VarienceAccount": null,
//             "DecreasingAccount": null,
//             "IncreasingAccount": null,
//             "ReturningAccount": null,
//             "ExpensesAccount": null,
//             "EURevenuesAccount": null,
//             "EUExpensesAccount": null,
//             "ForeignRevenueAcc": null,
//             "ForeignExpensAcc": null,
//             "ExemptIncomeAcc": null,
//             "PriceDifferenceAcc": null,
//             "WarehouseCode": "WCS",
//             "InStock": 0,
//             "Committed": 0,
//             "Ordered": 0,
//             "CountedQuantity": 0,
//             "WasCounted": "tNO",
//             "UserSignature": 20,
//             "Counted": 0,
//             "ExpenseClearingAct": null,
//             "PurchaseCreditAcc": null,
//             "EUPurchaseCreditAcc": null,
//             "ForeignPurchaseCreditAcc": null,
//             "SalesCreditAcc": null,
//             "SalesCreditEUAcc": null,
//             "ExemptedCredits": null,
//             "SalesCreditForeignAcc": null,
//             "ExpenseOffsettingAccount": null,
//             "WipAccount": null,
//             "ExchangeRateDifferencesAcct": null,
//             "GoodsClearingAcct": null,
//             "NegativeInventoryAdjustmentAccount": null,
//             "CostInflationOffsetAccount": null,
//             "GLDecreaseAcct": null,
//             "GLIncreaseAcct": null,
//             "PAReturnAcct": null,
//             "PurchaseAcct": null,
//             "PurchaseOffsetAcct": null,
//             "ShippedGoodsAccount": null,
//             "StockInflationOffsetAccount": null,
//             "StockInflationAdjustAccount": null,
//             "VATInRevenueAccount": null,
//             "WipVarianceAccount": null,
//             "CostInflationAccount": null,
//             "WHIncomingCenvatAccount": null,
//             "WHOutgoingCenvatAccount": null,
//             "StockInTransitAccount": null,
//             "WipOffsetProfitAndLossAccount": null,
//             "InventoryOffsetProfitAndLossAccount": null,
//             "DefaultBin": null,
//             "DefaultBinEnforced": "tNO",
//             "PurchaseBalanceAccount": null,
//             "ItemCode": "PLPID-0006",
//             "IndEscala": "tYES",
//             "CNJPMan": null,
//             "ItemCycleCounts": []
//         },
//         {
//             "MinimalStock": 0,
//             "MaximalStock": 0,
//             "MinimalOrder": 0,
//             "StandardAveragePrice": 0,
//             "Locked": "tNO",
//             "InventoryAccount": null,
//             "CostAccount": null,
//             "TransferAccount": null,
//             "RevenuesAccount": null,
//             "VarienceAccount": null,
//             "DecreasingAccount": null,
//             "IncreasingAccount": null,
//             "ReturningAccount": null,
//             "ExpensesAccount": null,
//             "EURevenuesAccount": null,
//             "EUExpensesAccount": null,
//             "ForeignRevenueAcc": null,
//             "ForeignExpensAcc": null,
//             "ExemptIncomeAcc": null,
//             "PriceDifferenceAcc": null,
//             "WarehouseCode": "WFP",
//             "InStock": 0,
//             "Committed": 0,
//             "Ordered": 0,
//             "CountedQuantity": 0,
//             "WasCounted": "tNO",
//             "UserSignature": 20,
//             "Counted": 0,
//             "ExpenseClearingAct": null,
//             "PurchaseCreditAcc": null,
//             "EUPurchaseCreditAcc": null,
//             "ForeignPurchaseCreditAcc": null,
//             "SalesCreditAcc": null,
//             "SalesCreditEUAcc": null,
//             "ExemptedCredits": null,
//             "SalesCreditForeignAcc": null,
//             "ExpenseOffsettingAccount": null,
//             "WipAccount": null,
//             "ExchangeRateDifferencesAcct": null,
//             "GoodsClearingAcct": null,
//             "NegativeInventoryAdjustmentAccount": null,
//             "CostInflationOffsetAccount": null,
//             "GLDecreaseAcct": null,
//             "GLIncreaseAcct": null,
//             "PAReturnAcct": null,
//             "PurchaseAcct": null,
//             "PurchaseOffsetAcct": null,
//             "ShippedGoodsAccount": null,
//             "StockInflationOffsetAccount": null,
//             "StockInflationAdjustAccount": null,
//             "VATInRevenueAccount": null,
//             "WipVarianceAccount": null,
//             "CostInflationAccount": null,
//             "WHIncomingCenvatAccount": null,
//             "WHOutgoingCenvatAccount": null,
//             "StockInTransitAccount": null,
//             "WipOffsetProfitAndLossAccount": null,
//             "InventoryOffsetProfitAndLossAccount": null,
//             "DefaultBin": null,
//             "DefaultBinEnforced": "tNO",
//             "PurchaseBalanceAccount": null,
//             "ItemCode": "PLPID-0006",
//             "IndEscala": "tYES",
//             "CNJPMan": null,
//             "ItemCycleCounts": []
//         },
//         {
//             "MinimalStock": 0,
//             "MaximalStock": 0,
//             "MinimalOrder": 0,
//             "StandardAveragePrice": 0,
//             "Locked": "tNO",
//             "InventoryAccount": null,
//             "CostAccount": null,
//             "TransferAccount": null,
//             "RevenuesAccount": null,
//             "VarienceAccount": null,
//             "DecreasingAccount": null,
//             "IncreasingAccount": null,
//             "ReturningAccount": null,
//             "ExpensesAccount": null,
//             "EURevenuesAccount": null,
//             "EUExpensesAccount": null,
//             "ForeignRevenueAcc": null,
//             "ForeignExpensAcc": null,
//             "ExemptIncomeAcc": null,
//             "PriceDifferenceAcc": null,
//             "WarehouseCode": "WIQ",
//             "InStock": 0,
//             "Committed": 0,
//             "Ordered": 0,
//             "CountedQuantity": 0,
//             "WasCounted": "tNO",
//             "UserSignature": 20,
//             "Counted": 0,
//             "ExpenseClearingAct": null,
//             "PurchaseCreditAcc": null,
//             "EUPurchaseCreditAcc": null,
//             "ForeignPurchaseCreditAcc": null,
//             "SalesCreditAcc": null,
//             "SalesCreditEUAcc": null,
//             "ExemptedCredits": null,
//             "SalesCreditForeignAcc": null,
//             "ExpenseOffsettingAccount": null,
//             "WipAccount": null,
//             "ExchangeRateDifferencesAcct": null,
//             "GoodsClearingAcct": null,
//             "NegativeInventoryAdjustmentAccount": null,
//             "CostInflationOffsetAccount": null,
//             "GLDecreaseAcct": null,
//             "GLIncreaseAcct": null,
//             "PAReturnAcct": null,
//             "PurchaseAcct": null,
//             "PurchaseOffsetAcct": null,
//             "ShippedGoodsAccount": null,
//             "StockInflationOffsetAccount": null,
//             "StockInflationAdjustAccount": null,
//             "VATInRevenueAccount": null,
//             "WipVarianceAccount": null,
//             "CostInflationAccount": null,
//             "WHIncomingCenvatAccount": null,
//             "WHOutgoingCenvatAccount": null,
//             "StockInTransitAccount": null,
//             "WipOffsetProfitAndLossAccount": null,
//             "InventoryOffsetProfitAndLossAccount": null,
//             "DefaultBin": null,
//             "DefaultBinEnforced": "tNO",
//             "PurchaseBalanceAccount": null,
//             "ItemCode": "PLPID-0006",
//             "IndEscala": "tYES",
//             "CNJPMan": null,
//             "ItemCycleCounts": []
//         },
//         {
//             "MinimalStock": 0,
//             "MaximalStock": 0,
//             "MinimalOrder": 0,
//             "StandardAveragePrice": 0,
//             "Locked": "tNO",
//             "InventoryAccount": null,
//             "CostAccount": null,
//             "TransferAccount": null,
//             "RevenuesAccount": null,
//             "VarienceAccount": null,
//             "DecreasingAccount": null,
//             "IncreasingAccount": null,
//             "ReturningAccount": null,
//             "ExpensesAccount": null,
//             "EURevenuesAccount": null,
//             "EUExpensesAccount": null,
//             "ForeignRevenueAcc": null,
//             "ForeignExpensAcc": null,
//             "ExemptIncomeAcc": null,
//             "PriceDifferenceAcc": null,
//             "WarehouseCode": "WPQ",
//             "InStock": 0,
//             "Committed": 0,
//             "Ordered": 0,
//             "CountedQuantity": 0,
//             "WasCounted": "tNO",
//             "UserSignature": 20,
//             "Counted": 0,
//             "ExpenseClearingAct": null,
//             "PurchaseCreditAcc": null,
//             "EUPurchaseCreditAcc": null,
//             "ForeignPurchaseCreditAcc": null,
//             "SalesCreditAcc": null,
//             "SalesCreditEUAcc": null,
//             "ExemptedCredits": null,
//             "SalesCreditForeignAcc": null,
//             "ExpenseOffsettingAccount": null,
//             "WipAccount": null,
//             "ExchangeRateDifferencesAcct": null,
//             "GoodsClearingAcct": null,
//             "NegativeInventoryAdjustmentAccount": null,
//             "CostInflationOffsetAccount": null,
//             "GLDecreaseAcct": null,
//             "GLIncreaseAcct": null,
//             "PAReturnAcct": null,
//             "PurchaseAcct": null,
//             "PurchaseOffsetAcct": null,
//             "ShippedGoodsAccount": null,
//             "StockInflationOffsetAccount": null,
//             "StockInflationAdjustAccount": null,
//             "VATInRevenueAccount": null,
//             "WipVarianceAccount": null,
//             "CostInflationAccount": null,
//             "WHIncomingCenvatAccount": null,
//             "WHOutgoingCenvatAccount": null,
//             "StockInTransitAccount": null,
//             "WipOffsetProfitAndLossAccount": null,
//             "InventoryOffsetProfitAndLossAccount": null,
//             "DefaultBin": null,
//             "DefaultBinEnforced": "tNO",
//             "PurchaseBalanceAccount": null,
//             "ItemCode": "PLPID-0006",
//             "IndEscala": "tYES",
//             "CNJPMan": null,
//             "ItemCycleCounts": []
//         },
//         {
//             "MinimalStock": 0,
//             "MaximalStock": 0,
//             "MinimalOrder": 0,
//             "StandardAveragePrice": 0,
//             "Locked": "tNO",
//             "InventoryAccount": null,
//             "CostAccount": null,
//             "TransferAccount": null,
//             "RevenuesAccount": null,
//             "VarienceAccount": null,
//             "DecreasingAccount": null,
//             "IncreasingAccount": null,
//             "ReturningAccount": null,
//             "ExpensesAccount": null,
//             "EURevenuesAccount": null,
//             "EUExpensesAccount": null,
//             "ForeignRevenueAcc": null,
//             "ForeignExpensAcc": null,
//             "ExemptIncomeAcc": null,
//             "PriceDifferenceAcc": null,
//             "WarehouseCode": "WPR",
//             "InStock": 0,
//             "Committed": 0,
//             "Ordered": 0,
//             "CountedQuantity": 0,
//             "WasCounted": "tNO",
//             "UserSignature": 20,
//             "Counted": 0,
//             "ExpenseClearingAct": null,
//             "PurchaseCreditAcc": null,
//             "EUPurchaseCreditAcc": null,
//             "ForeignPurchaseCreditAcc": null,
//             "SalesCreditAcc": null,
//             "SalesCreditEUAcc": null,
//             "ExemptedCredits": null,
//             "SalesCreditForeignAcc": null,
//             "ExpenseOffsettingAccount": null,
//             "WipAccount": null,
//             "ExchangeRateDifferencesAcct": null,
//             "GoodsClearingAcct": null,
//             "NegativeInventoryAdjustmentAccount": null,
//             "CostInflationOffsetAccount": null,
//             "GLDecreaseAcct": null,
//             "GLIncreaseAcct": null,
//             "PAReturnAcct": null,
//             "PurchaseAcct": null,
//             "PurchaseOffsetAcct": null,
//             "ShippedGoodsAccount": null,
//             "StockInflationOffsetAccount": null,
//             "StockInflationAdjustAccount": null,
//             "VATInRevenueAccount": null,
//             "WipVarianceAccount": null,
//             "CostInflationAccount": null,
//             "WHIncomingCenvatAccount": null,
//             "WHOutgoingCenvatAccount": null,
//             "StockInTransitAccount": null,
//             "WipOffsetProfitAndLossAccount": null,
//             "InventoryOffsetProfitAndLossAccount": null,
//             "DefaultBin": null,
//             "DefaultBinEnforced": "tNO",
//             "PurchaseBalanceAccount": null,
//             "ItemCode": "PLPID-0006",
//             "IndEscala": "tYES",
//             "CNJPMan": null,
//             "ItemCycleCounts": []
//         },
//         {
//             "MinimalStock": 0,
//             "MaximalStock": 0,
//             "MinimalOrder": 0,
//             "StandardAveragePrice": 0,
//             "Locked": "tNO",
//             "InventoryAccount": null,
//             "CostAccount": null,
//             "TransferAccount": null,
//             "RevenuesAccount": null,
//             "VarienceAccount": null,
//             "DecreasingAccount": null,
//             "IncreasingAccount": null,
//             "ReturningAccount": null,
//             "ExpensesAccount": null,
//             "EURevenuesAccount": null,
//             "EUExpensesAccount": null,
//             "ForeignRevenueAcc": null,
//             "ForeignExpensAcc": null,
//             "ExemptIncomeAcc": null,
//             "PriceDifferenceAcc": null,
//             "WarehouseCode": "WRJ",
//             "InStock": 0,
//             "Committed": 0,
//             "Ordered": 0,
//             "CountedQuantity": 0,
//             "WasCounted": "tNO",
//             "UserSignature": 20,
//             "Counted": 0,
//             "ExpenseClearingAct": null,
//             "PurchaseCreditAcc": null,
//             "EUPurchaseCreditAcc": null,
//             "ForeignPurchaseCreditAcc": null,
//             "SalesCreditAcc": null,
//             "SalesCreditEUAcc": null,
//             "ExemptedCredits": null,
//             "SalesCreditForeignAcc": null,
//             "ExpenseOffsettingAccount": null,
//             "WipAccount": null,
//             "ExchangeRateDifferencesAcct": null,
//             "GoodsClearingAcct": null,
//             "NegativeInventoryAdjustmentAccount": null,
//             "CostInflationOffsetAccount": null,
//             "GLDecreaseAcct": null,
//             "GLIncreaseAcct": null,
//             "PAReturnAcct": null,
//             "PurchaseAcct": null,
//             "PurchaseOffsetAcct": null,
//             "ShippedGoodsAccount": null,
//             "StockInflationOffsetAccount": null,
//             "StockInflationAdjustAccount": null,
//             "VATInRevenueAccount": null,
//             "WipVarianceAccount": null,
//             "CostInflationAccount": null,
//             "WHIncomingCenvatAccount": null,
//             "WHOutgoingCenvatAccount": null,
//             "StockInTransitAccount": null,
//             "WipOffsetProfitAndLossAccount": null,
//             "InventoryOffsetProfitAndLossAccount": null,
//             "DefaultBin": null,
//             "DefaultBinEnforced": "tNO",
//             "PurchaseBalanceAccount": null,
//             "ItemCode": "PLPID-0006",
//             "IndEscala": "tYES",
//             "CNJPMan": null,
//             "ItemCycleCounts": []
//         },
//         {
//             "MinimalStock": 0,
//             "MaximalStock": 0,
//             "MinimalOrder": 0,
//             "StandardAveragePrice": 0,
//             "Locked": "tNO",
//             "InventoryAccount": null,
//             "CostAccount": null,
//             "TransferAccount": null,
//             "RevenuesAccount": null,
//             "VarienceAccount": null,
//             "DecreasingAccount": null,
//             "IncreasingAccount": null,
//             "ReturningAccount": null,
//             "ExpensesAccount": null,
//             "EURevenuesAccount": null,
//             "EUExpensesAccount": null,
//             "ForeignRevenueAcc": null,
//             "ForeignExpensAcc": null,
//             "ExemptIncomeAcc": null,
//             "PriceDifferenceAcc": null,
//             "WarehouseCode": "WRT",
//             "InStock": 0,
//             "Committed": 0,
//             "Ordered": 0,
//             "CountedQuantity": 0,
//             "WasCounted": "tNO",
//             "UserSignature": 20,
//             "Counted": 0,
//             "ExpenseClearingAct": null,
//             "PurchaseCreditAcc": null,
//             "EUPurchaseCreditAcc": null,
//             "ForeignPurchaseCreditAcc": null,
//             "SalesCreditAcc": null,
//             "SalesCreditEUAcc": null,
//             "ExemptedCredits": null,
//             "SalesCreditForeignAcc": null,
//             "ExpenseOffsettingAccount": null,
//             "WipAccount": null,
//             "ExchangeRateDifferencesAcct": null,
//             "GoodsClearingAcct": null,
//             "NegativeInventoryAdjustmentAccount": null,
//             "CostInflationOffsetAccount": null,
//             "GLDecreaseAcct": null,
//             "GLIncreaseAcct": null,
//             "PAReturnAcct": null,
//             "PurchaseAcct": null,
//             "PurchaseOffsetAcct": null,
//             "ShippedGoodsAccount": null,
//             "StockInflationOffsetAccount": null,
//             "StockInflationAdjustAccount": null,
//             "VATInRevenueAccount": null,
//             "WipVarianceAccount": null,
//             "CostInflationAccount": null,
//             "WHIncomingCenvatAccount": null,
//             "WHOutgoingCenvatAccount": null,
//             "StockInTransitAccount": null,
//             "WipOffsetProfitAndLossAccount": null,
//             "InventoryOffsetProfitAndLossAccount": null,
//             "DefaultBin": null,
//             "DefaultBinEnforced": "tNO",
//             "PurchaseBalanceAccount": null,
//             "ItemCode": "PLPID-0006",
//             "IndEscala": "tYES",
//             "CNJPMan": null,
//             "ItemCycleCounts": []
//         },
//         {
//             "MinimalStock": 0,
//             "MaximalStock": 0,
//             "MinimalOrder": 0,
//             "StandardAveragePrice": 0,
//             "Locked": "tNO",
//             "InventoryAccount": null,
//             "CostAccount": null,
//             "TransferAccount": null,
//             "RevenuesAccount": null,
//             "VarienceAccount": null,
//             "DecreasingAccount": null,
//             "IncreasingAccount": null,
//             "ReturningAccount": null,
//             "ExpensesAccount": null,
//             "EURevenuesAccount": null,
//             "EUExpensesAccount": null,
//             "ForeignRevenueAcc": null,
//             "ForeignExpensAcc": null,
//             "ExemptIncomeAcc": null,
//             "PriceDifferenceAcc": null,
//             "WarehouseCode": "WRV",
//             "InStock": 0,
//             "Committed": 0,
//             "Ordered": 0,
//             "CountedQuantity": 0,
//             "WasCounted": "tNO",
//             "UserSignature": 20,
//             "Counted": 0,
//             "ExpenseClearingAct": null,
//             "PurchaseCreditAcc": null,
//             "EUPurchaseCreditAcc": null,
//             "ForeignPurchaseCreditAcc": null,
//             "SalesCreditAcc": null,
//             "SalesCreditEUAcc": null,
//             "ExemptedCredits": null,
//             "SalesCreditForeignAcc": null,
//             "ExpenseOffsettingAccount": null,
//             "WipAccount": null,
//             "ExchangeRateDifferencesAcct": null,
//             "GoodsClearingAcct": null,
//             "NegativeInventoryAdjustmentAccount": null,
//             "CostInflationOffsetAccount": null,
//             "GLDecreaseAcct": null,
//             "GLIncreaseAcct": null,
//             "PAReturnAcct": null,
//             "PurchaseAcct": null,
//             "PurchaseOffsetAcct": null,
//             "ShippedGoodsAccount": null,
//             "StockInflationOffsetAccount": null,
//             "StockInflationAdjustAccount": null,
//             "VATInRevenueAccount": null,
//             "WipVarianceAccount": null,
//             "CostInflationAccount": null,
//             "WHIncomingCenvatAccount": null,
//             "WHOutgoingCenvatAccount": null,
//             "StockInTransitAccount": null,
//             "WipOffsetProfitAndLossAccount": null,
//             "InventoryOffsetProfitAndLossAccount": null,
//             "DefaultBin": null,
//             "DefaultBinEnforced": "tNO",
//             "PurchaseBalanceAccount": null,
//             "ItemCode": "PLPID-0006",
//             "IndEscala": "tYES",
//             "CNJPMan": null,
//             "ItemCycleCounts": []
//         },
//         {
//             "MinimalStock": 0,
//             "MaximalStock": 0,
//             "MinimalOrder": 0,
//             "StandardAveragePrice": 0,
//             "Locked": "tNO",
//             "InventoryAccount": null,
//             "CostAccount": null,
//             "TransferAccount": null,
//             "RevenuesAccount": null,
//             "VarienceAccount": null,
//             "DecreasingAccount": null,
//             "IncreasingAccount": null,
//             "ReturningAccount": null,
//             "ExpensesAccount": null,
//             "EURevenuesAccount": null,
//             "EUExpensesAccount": null,
//             "ForeignRevenueAcc": null,
//             "ForeignExpensAcc": null,
//             "ExemptIncomeAcc": null,
//             "PriceDifferenceAcc": null,
//             "WarehouseCode": "WS1",
//             "InStock": 0,
//             "Committed": 0,
//             "Ordered": 0,
//             "CountedQuantity": 0,
//             "WasCounted": "tNO",
//             "UserSignature": 20,
//             "Counted": 0,
//             "ExpenseClearingAct": null,
//             "PurchaseCreditAcc": null,
//             "EUPurchaseCreditAcc": null,
//             "ForeignPurchaseCreditAcc": null,
//             "SalesCreditAcc": null,
//             "SalesCreditEUAcc": null,
//             "ExemptedCredits": null,
//             "SalesCreditForeignAcc": null,
//             "ExpenseOffsettingAccount": null,
//             "WipAccount": null,
//             "ExchangeRateDifferencesAcct": null,
//             "GoodsClearingAcct": null,
//             "NegativeInventoryAdjustmentAccount": null,
//             "CostInflationOffsetAccount": null,
//             "GLDecreaseAcct": null,
//             "GLIncreaseAcct": null,
//             "PAReturnAcct": null,
//             "PurchaseAcct": null,
//             "PurchaseOffsetAcct": null,
//             "ShippedGoodsAccount": null,
//             "StockInflationOffsetAccount": null,
//             "StockInflationAdjustAccount": null,
//             "VATInRevenueAccount": null,
//             "WipVarianceAccount": null,
//             "CostInflationAccount": null,
//             "WHIncomingCenvatAccount": null,
//             "WHOutgoingCenvatAccount": null,
//             "StockInTransitAccount": null,
//             "WipOffsetProfitAndLossAccount": null,
//             "InventoryOffsetProfitAndLossAccount": null,
//             "DefaultBin": null,
//             "DefaultBinEnforced": "tNO",
//             "PurchaseBalanceAccount": null,
//             "ItemCode": "PLPID-0006",
//             "IndEscala": "tYES",
//             "CNJPMan": null,
//             "ItemCycleCounts": []
//         },
//         {
//             "MinimalStock": 0,
//             "MaximalStock": 0,
//             "MinimalOrder": 0,
//             "StandardAveragePrice": 0,
//             "Locked": "tNO",
//             "InventoryAccount": null,
//             "CostAccount": null,
//             "TransferAccount": null,
//             "RevenuesAccount": null,
//             "VarienceAccount": null,
//             "DecreasingAccount": null,
//             "IncreasingAccount": null,
//             "ReturningAccount": null,
//             "ExpensesAccount": null,
//             "EURevenuesAccount": null,
//             "EUExpensesAccount": null,
//             "ForeignRevenueAcc": null,
//             "ForeignExpensAcc": null,
//             "ExemptIncomeAcc": null,
//             "PriceDifferenceAcc": null,
//             "WarehouseCode": "WS2",
//             "InStock": 0,
//             "Committed": 0,
//             "Ordered": 0,
//             "CountedQuantity": 0,
//             "WasCounted": "tNO",
//             "UserSignature": 20,
//             "Counted": 0,
//             "ExpenseClearingAct": null,
//             "PurchaseCreditAcc": null,
//             "EUPurchaseCreditAcc": null,
//             "ForeignPurchaseCreditAcc": null,
//             "SalesCreditAcc": null,
//             "SalesCreditEUAcc": null,
//             "ExemptedCredits": null,
//             "SalesCreditForeignAcc": null,
//             "ExpenseOffsettingAccount": null,
//             "WipAccount": null,
//             "ExchangeRateDifferencesAcct": null,
//             "GoodsClearingAcct": null,
//             "NegativeInventoryAdjustmentAccount": null,
//             "CostInflationOffsetAccount": null,
//             "GLDecreaseAcct": null,
//             "GLIncreaseAcct": null,
//             "PAReturnAcct": null,
//             "PurchaseAcct": null,
//             "PurchaseOffsetAcct": null,
//             "ShippedGoodsAccount": null,
//             "StockInflationOffsetAccount": null,
//             "StockInflationAdjustAccount": null,
//             "VATInRevenueAccount": null,
//             "WipVarianceAccount": null,
//             "CostInflationAccount": null,
//             "WHIncomingCenvatAccount": null,
//             "WHOutgoingCenvatAccount": null,
//             "StockInTransitAccount": null,
//             "WipOffsetProfitAndLossAccount": null,
//             "InventoryOffsetProfitAndLossAccount": null,
//             "DefaultBin": null,
//             "DefaultBinEnforced": "tNO",
//             "PurchaseBalanceAccount": null,
//             "ItemCode": "PLPID-0006",
//             "IndEscala": "tYES",
//             "CNJPMan": null,
//             "ItemCycleCounts": []
//         },
//         {
//             "MinimalStock": 0,
//             "MaximalStock": 0,
//             "MinimalOrder": 0,
//             "StandardAveragePrice": 0,
//             "Locked": "tNO",
//             "InventoryAccount": null,
//             "CostAccount": null,
//             "TransferAccount": null,
//             "RevenuesAccount": null,
//             "VarienceAccount": null,
//             "DecreasingAccount": null,
//             "IncreasingAccount": null,
//             "ReturningAccount": null,
//             "ExpensesAccount": null,
//             "EURevenuesAccount": null,
//             "EUExpensesAccount": null,
//             "ForeignRevenueAcc": null,
//             "ForeignExpensAcc": null,
//             "ExemptIncomeAcc": null,
//             "PriceDifferenceAcc": null,
//             "WarehouseCode": "WSE",
//             "InStock": 0,
//             "Committed": 0,
//             "Ordered": 0,
//             "CountedQuantity": 0,
//             "WasCounted": "tNO",
//             "UserSignature": 20,
//             "Counted": 0,
//             "ExpenseClearingAct": null,
//             "PurchaseCreditAcc": null,
//             "EUPurchaseCreditAcc": null,
//             "ForeignPurchaseCreditAcc": null,
//             "SalesCreditAcc": null,
//             "SalesCreditEUAcc": null,
//             "ExemptedCredits": null,
//             "SalesCreditForeignAcc": null,
//             "ExpenseOffsettingAccount": null,
//             "WipAccount": null,
//             "ExchangeRateDifferencesAcct": null,
//             "GoodsClearingAcct": null,
//             "NegativeInventoryAdjustmentAccount": null,
//             "CostInflationOffsetAccount": null,
//             "GLDecreaseAcct": null,
//             "GLIncreaseAcct": null,
//             "PAReturnAcct": null,
//             "PurchaseAcct": null,
//             "PurchaseOffsetAcct": null,
//             "ShippedGoodsAccount": null,
//             "StockInflationOffsetAccount": null,
//             "StockInflationAdjustAccount": null,
//             "VATInRevenueAccount": null,
//             "WipVarianceAccount": null,
//             "CostInflationAccount": null,
//             "WHIncomingCenvatAccount": null,
//             "WHOutgoingCenvatAccount": null,
//             "StockInTransitAccount": null,
//             "WipOffsetProfitAndLossAccount": null,
//             "InventoryOffsetProfitAndLossAccount": null,
//             "DefaultBin": null,
//             "DefaultBinEnforced": "tNO",
//             "PurchaseBalanceAccount": null,
//             "ItemCode": "PLPID-0006",
//             "IndEscala": "tYES",
//             "CNJPMan": null,
//             "ItemCycleCounts": []
//         },
//         {
//             "MinimalStock": 0,
//             "MaximalStock": 0,
//             "MinimalOrder": 0,
//             "StandardAveragePrice": 0,
//             "Locked": "tNO",
//             "InventoryAccount": null,
//             "CostAccount": null,
//             "TransferAccount": null,
//             "RevenuesAccount": null,
//             "VarienceAccount": null,
//             "DecreasingAccount": null,
//             "IncreasingAccount": null,
//             "ReturningAccount": null,
//             "ExpensesAccount": null,
//             "EURevenuesAccount": null,
//             "EUExpensesAccount": null,
//             "ForeignRevenueAcc": null,
//             "ForeignExpensAcc": null,
//             "ExemptIncomeAcc": null,
//             "PriceDifferenceAcc": null,
//             "WarehouseCode": "WSP",
//             "InStock": 0,
//             "Committed": 0,
//             "Ordered": 0,
//             "CountedQuantity": 0,
//             "WasCounted": "tNO",
//             "UserSignature": 20,
//             "Counted": 0,
//             "ExpenseClearingAct": null,
//             "PurchaseCreditAcc": null,
//             "EUPurchaseCreditAcc": null,
//             "ForeignPurchaseCreditAcc": null,
//             "SalesCreditAcc": null,
//             "SalesCreditEUAcc": null,
//             "ExemptedCredits": null,
//             "SalesCreditForeignAcc": null,
//             "ExpenseOffsettingAccount": null,
//             "WipAccount": null,
//             "ExchangeRateDifferencesAcct": null,
//             "GoodsClearingAcct": null,
//             "NegativeInventoryAdjustmentAccount": null,
//             "CostInflationOffsetAccount": null,
//             "GLDecreaseAcct": null,
//             "GLIncreaseAcct": null,
//             "PAReturnAcct": null,
//             "PurchaseAcct": null,
//             "PurchaseOffsetAcct": null,
//             "ShippedGoodsAccount": null,
//             "StockInflationOffsetAccount": null,
//             "StockInflationAdjustAccount": null,
//             "VATInRevenueAccount": null,
//             "WipVarianceAccount": null,
//             "CostInflationAccount": null,
//             "WHIncomingCenvatAccount": null,
//             "WHOutgoingCenvatAccount": null,
//             "StockInTransitAccount": null,
//             "WipOffsetProfitAndLossAccount": null,
//             "InventoryOffsetProfitAndLossAccount": null,
//             "DefaultBin": null,
//             "DefaultBinEnforced": "tNO",
//             "PurchaseBalanceAccount": null,
//             "ItemCode": "PLPID-0006",
//             "IndEscala": "tYES",
//             "CNJPMan": null,
//             "ItemCycleCounts": []
//         }
//     ],
//     "ItemPreferredVendors": [],
//     "ItemLocalizationInfos": [],
//     "ItemProjects": [],
//     "ItemDistributionRules": [],
//     "ItemAttributeGroups": [],
//     "ItemDepreciationParameters": [],
//     "ItemPeriodControls": [],
//     "ItemUnitOfMeasurementCollection": [],
//     "ItemBarCodeCollection": [],
//     "ItemIntrastatExtension": {
//         "ItemCode": "PLPID-0006",
//         "CommodityCode": null,
//         "SupplementaryUnit": null,
//         "FactorOfSupplementaryUnit": 0,
//         "ImportRegionState": null,
//         "ExportRegionState": null,
//         "ImportNatureOfTransaction": null,
//         "ExportNatureOfTransaction": null,
//         "ImportStatisticalProcedure": null,
//         "ExportStatisticalProcedure": null,
//         "CountryOfOrigin": null,
//         "ServiceCode": null,
//         "Type": "dDocument_Items",
//         "ServiceSupplyMethod": "ssmImmediate",
//         "ServicePaymentMethod": "spmOther",
//         "ImportRegionCountry": null,
//         "ExportRegionCountry": null,
//         "UseWeightInCalculation": "tYES",
//         "IntrastatRelevant": "tNO",
//         "StatisticalCode": null
//     }
// }

});

// BinLocations
app.post("/api/binlocations", async (req, res) => {
  console.log("req.body:", req.body);
  const getBinLocationBaseURL = `https://192.168.0.44:50000/b1s/v1/BinLocations?$select=AbsEntry,BinCode,Warehouse&$filter=Warehouse eq '${req.body.WarehouseCode}'`;
  console.log(getBinLocationBaseURL);
  console.log("sessionObj.sessionId: " + sessionObj.sessionId);
  try {
    const response = await axios.get(getBinLocationBaseURL, {
      withCredentials: true,
      headers: {
        Cookie: sessionObj.sessionId,
        Prefer: "odata.maxpagesize=9999999999",
      },
    });
    res.send(response.data);
  } catch (error) {
    console.log("error.message:", error.message);
    res.status(500).send(error.message);
  }
});

// Batch in Bin and Qty
app.post("/api/batchinbin", async (req, res) => {
  console.log("req.body:", req.body);
  const getBatchInBinBaseURL = `https://192.168.0.44:50000/b1s/v1/view.svc/Homart_BatchInBinQty_B1SLQuery()?$filter=DistNumber eq '${req.body.BatchNumber}' and OnHandQty gt 0`;
  console.log(getBatchInBinBaseURL);
  console.log("sessionObj.sessionId: " + sessionObj.sessionId);
  try {
    const response = await axios.get(getBatchInBinBaseURL, {
      withCredentials: true,
      headers: {
        Cookie: sessionObj.sessionId,
        Prefer: "odata.maxpagesize=9999999999",
      },
    });
    res.send(response.data);
  } catch (error) {
    console.log("error.message:", error.message);
    res.status(500).send(error.message);
  }

  // Sample Response
  //   {
  //     "odata.metadata": "https://192.168.0.44:50000/b1s/v1/view.svc/$metadata#Homart_BatchInBinQty_B1SLQuery",
  //     "value": [
  //         {
  //             "ItemCode": "PC038-0010",
  //             "ItemName": "Cap 1HOM 38mm Gold Cap for RA300/185 with Induction Seal - JX",
  //             "DistNumber": "H36593",
  //             "batchabsebntry": 19426,
  //             "WhsCode": "WCP",
  //             "WhsName": "Component warehouse",
  //             "BinAbs": 671,
  //             "BinCode": "WCP-1K20-1",
  //             "OnHandQty": 19208,
  //             "id__": 1
  //         }
  //     ]
  // }
});

// Get Journal Memo, This is the notes for the Web Transfer
app.post("/api/journalmemo", async (req, res) => {
  console.log("req.body:", req.body);
  const getJournalMemoBaseURL = `https://192.168.0.44:50000/b1s/v1/view.svc/Homart_JournalMemo_B1SLQuery()`;
  console.log(getJournalMemoBaseURL);
  console.log("sessionObj.sessionId: " + sessionObj.sessionId);
  try {
    const response = await axios.get(getJournalMemoBaseURL, {
      withCredentials: true,
      headers: {
        Cookie: sessionObj.sessionId,
        Prefer: "odata.maxpagesize=9999999999",
      },
    });
    res.send(response.data);
  } catch (error) {
    console.log("error.message:", error.message);
    res.status(500).send(error.message);
  }

  // Sample Response
  //   {
  //     "odata.metadata": "https://192.168.0.44:50000/b1s/v1/view.svc/$metadata#Homart_JournalMemo_B1SLQuery",
  //     "value": [
  //         {
  //             "JrnlMemo": "WEB STOCK Transferno:202307280005",
  //             "id__": 1
  //         }
  //     ]
  // }
});

app.listen(port, () => {
  console.log("Server listening on port " + port);
  loginToSAPSession();
  setInterval(loginToSAPSession, 28 * 60 * 1000);
});
